import React, { useState } from "react";
import { auth } from "../lib/firebase";
import { Shield, LogIn } from "lucide-react";
import { signInWithEmailAndPassword, signInWithCustomToken, createUserWithEmailAndPassword } from "firebase/auth";
import { motion } from "motion/react";
import { cn } from "../lib/utils";
import { PlatformLogo } from "./PlatformLogo";

import { UserProfile } from "../types";

export function Login({
  onLogin,
}: {
  onLogin?: (profile: UserProfile) => void;
}) {
  const [loading, setLoading] = useState(false);
  const [formData, setFormData] = useState({ rg: "", password: "" });
  const [error, setError] = useState<string | null>(null);

  const [isRecovering, setIsRecovering] = useState(false);
  const [recoverData, setRecoverData] = useState({
    rg: "",
    dataNascimento: "",
  });
  const [recoverLoading, setRecoverLoading] = useState(false);
  const [recoverSuccess, setRecoverSuccess] = useState<string | null>(null);

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setError(null);

    // 0. Clear any old session state BEFORE starting new login
    localStorage.removeItem("militar_profile");
    localStorage.removeItem("militar_verify_code");
    localStorage.removeItem("cache_permutas");

    try {
      // 1. Post to secure server-side login
      const response = await fetch("/api/login", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ rg: formData.rg, password: formData.password }),
      }).catch(() => {
        throw new Error("Erro de conexão com o servidor. Por favor, aguarde alguns instantes enquanto o sistema inicializa e tente novamente.");
      });

      const data = await response.json();
      if (!response.ok || !data.success) {
         throw new Error(data.error || "RG ou Senha incorretos");
      }

      const profileData = data.profile;

      // 2. Client sign-in securely via Custom Token or Email/Password generated by our server
      // We do this in the background, without blocking the login flow, or we skip it if it fails.
      if (data.useClientAuth && data.authEmail && data.authPassword) {
        try {
           const attemptSignIn = async (retries = 3, delay = 500) => {
             for (let i = 0; i < retries; i++) {
               try {
                 await signInWithEmailAndPassword(auth, data.authEmail, data.authPassword);
                 return true; // Success
               } catch (authErr: any) {
                 if (authErr.code === 'auth/user-not-found' || data.needsClientRegistration) {
                    try {
                       await createUserWithEmailAndPassword(auth, data.authEmail, data.authPassword);
                       return true;
                    } catch (createErr: any) {
                       if (createErr.code === 'auth/email-already-in-use') {
                           // Continue to retry sign in
                       } else if (createErr.code !== 'auth/operation-not-allowed') {
                           console.warn("[Auth] Client registration failed or not allowed.", createErr.message);
                           throw createErr;
                       }
                    }
                 } else if (authErr.code === 'auth/invalid-credential' && i < retries - 1) {
                    // Password might still be propagating in Firebase backend. Wait and retry.
                    await new Promise(resolve => setTimeout(resolve, delay));
                    continue;
                 } else if (authErr.code !== 'auth/operation-not-allowed') {
                    console.warn("[Auth] Client email/password sign-in failed.", authErr.message);
                    throw authErr;
                 }
               }
             }
           };
           
           await attemptSignIn().catch(() => {});
        } catch(e) { console.warn("Failed to load firebase/auth", e) }
      } else if (data.token) {
        try {
           try {
             await signInWithCustomToken(auth, data.token);
           } catch (authErr: any) {
             console.warn("[Auth] Client custom-token sign-in failed.", authErr.message);
           }
        } catch(e) { console.warn("Failed to load firebase/auth", e) }
      }

      localStorage.setItem("militar_profile", JSON.stringify(profileData));
      
      if (onLogin) {
        onLogin(profileData);
      } else {
        window.location.href = `${window.location.origin}/?v=${Date.now()}`;
      }
      
    } catch (err: any) {
      console.error('Login error', err);
      setError(err.message || "Erro de conexão com a autenticação");
    } finally {
      const hasProfile = !!localStorage.getItem("militar_profile");
      if (!hasProfile) setLoading(false);
    }
  };

  const handleRecover = async (e: React.FormEvent) => {
    e.preventDefault();
    setRecoverLoading(true);
    setError(null);
    setRecoverSuccess(null);

    try {
      const response = await fetch("/api/recover-password", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(recoverData),
      });

      const data = await response.json();

      if (response.ok && data.success) {
        setRecoverSuccess(
          "Senha redefinida com sucesso! Você já pode acessar o sistema utilizando sua Data de Nascimento (DDMMYYYY) como senha.",
        );
        setTimeout(() => setIsRecovering(false), 5000);
      } else {
        setError(
          data.error || "Erro ao recuperar senha. Verifique seus dados.",
        );
      }
    } catch (err) {
      console.error(err);
      setError("Erro de conexão com o servidor");
    } finally {
      setRecoverLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-[var(--color-bg-main)] flex items-center justify-center sm:p-6 lg:p-12">
      <motion.div
        initial={{ opacity: 0, scale: 0.98 }}
        animate={{ opacity: 1, scale: 1 }}
        className="w-full flex flex-col min-h-screen sm:min-h-0 sm:flex-none sm:max-w-lg bg-white sm:rounded-2xl shadow-2xl border-0 sm:border border-slate-200 overflow-hidden relative z-10"
      >
        <div className="bg-[var(--color-brand-dark)] p-8 lg:p-12 text-white text-center flex flex-col items-center border-b-4 border-[var(--color-brand-red)] shrink-0 pt-16 sm:pt-12">
          <div className="w-[100px] h-[100px] bg-white rounded-full flex items-center justify-center p-0 mb-6 overflow-hidden shadow-inner shrink-0">
            <PlatformLogo className="w-[100px] h-[100px] text-[var(--color-brand-dark)] scale-[1.25]" />
          </div>
          <h2 className="text-4xl sm:text-5xl font-black tracking-tighter leading-none mb-4 uppercase">
            CONEXÃO BRAVO
          </h2>
          <div className="flex items-center gap-3">
            <div className="w-10 h-0.5 bg-white/20" />
            <p className="text-white/60 font-mono text-sm sm:text-base uppercase tracking-[0.2em]">
              CBA VII - COSTA VERDE
            </p>
            <div className="w-10 h-0.5 bg-white/20" />
          </div>
        </div>

        <div className="p-8 lg:p-12 flex flex-col flex-1 justify-center sm:block">
          {isRecovering ? (
            <form onSubmit={handleRecover} className="space-y-6">
              <div className="text-center mb-8">
                <p className="text-slate-500 font-bold text-xs leading-relaxed uppercase tracking-wider">
                  Recuperação de Senha <br />
                  Informe seu RG e Data de Nascimento para restaurar a senha
                  padrão.
                </p>
              </div>

              {error && (
                <div className="p-4 bg-red-50 border border-red-100 rounded text-red-600 text-xs font-bold uppercase tracking-tight text-center">
                  {error}
                </div>
              )}

              {recoverSuccess && (
                <div className="p-4 bg-emerald-50 border border-emerald-100 rounded text-emerald-600 text-xs font-bold uppercase tracking-tight text-center">
                  {recoverSuccess}
                </div>
              )}

              {!recoverSuccess && (
                <>
                  <div className="space-y-5">
                    <div>
                      <label className="block text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1.5 ml-1">
                        RG Militar
                      </label>
                      <input
                        type="text"
                        required
                        placeholder="DIGITE SEU RG"
                        value={recoverData.rg}
                        onChange={(e) =>
                          setRecoverData((prev) => ({
                            ...prev,
                            rg: e.target.value,
                          }))
                        }
                        className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded focus:border-[var(--color-brand-dark)] focus:ring-0 transition-all font-mono text-xs text-slate-700 placeholder:text-slate-300 uppercase"
                      />
                    </div>
                    <div>
                      <label className="block text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1.5 ml-1">
                        Data de Nascimento
                      </label>
                      <input
                        type="text"
                        required
                        placeholder="DDMMYYYY"
                        value={recoverData.dataNascimento}
                        onChange={(e) =>
                          setRecoverData((prev) => ({
                            ...prev,
                            dataNascimento: e.target.value,
                          }))
                        }
                        className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded focus:border-[var(--color-brand-dark)] focus:ring-0 transition-all font-mono text-xs text-slate-700 placeholder:text-slate-300 uppercase"
                      />
                    </div>
                  </div>

                  <button
                    type="submit"
                    disabled={recoverLoading}
                    className="w-full flex items-center justify-center gap-4 bg-[var(--color-brand-dark)] text-white py-4 rounded font-black shadow-lg hover:shadow-xl hover:bg-black transition-all group disabled:opacity-50 uppercase text-xs tracking-widest"
                  >
                    {recoverLoading ? "PROCESSANDO..." : "Recuperar Senha"}
                  </button>
                </>
              )}

              <div className="mt-6 text-center">
                <button
                  type="button"
                  onClick={() => {
                    setIsRecovering(false);
                    setError(null);
                    setRecoverSuccess(null);
                  }}
                  className="text-[10px] font-bold text-slate-400 uppercase tracking-widest hover:text-[var(--color-brand-dark)]"
                >
                  Voltar para o Login
                </button>
              </div>
            </form>
          ) : (
            <form onSubmit={handleLogin} className="space-y-6">
              <div className="text-center mb-8">
                <p className="text-slate-500 font-bold text-xs leading-relaxed uppercase tracking-wider">
                  {loading && !!localStorage.getItem("militar_profile") ? (
                    <span className="text-amber-600 animate-pulse">
                      Sincronizando Sessão Final... Aguarde.
                    </span>
                  ) : (
                    <>
                      Acesso restrito a militares do Corpo de Bombeiros. <br />
                      Utilize seu RG e Senha.
                    </>
                  )}
                </p>
              </div>

              {error && (
                <div className="p-4 bg-red-50 border border-red-100 rounded text-red-600 text-xs font-bold uppercase tracking-tight text-center">
                  {error}
                </div>
              )}

              <div className="space-y-5">
                <div>
                  <label className="block text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1.5 ml-1">
                    RG Militar
                  </label>
                  <input
                    type="text"
                    required
                    placeholder="DIGITE SEU RG"
                    value={formData.rg}
                    onChange={(e) =>
                      setFormData((prev) => ({ ...prev, rg: e.target.value }))
                    }
                    className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded focus:border-[var(--color-brand-dark)] focus:ring-0 transition-all font-mono text-xs text-slate-700 placeholder:text-slate-300 uppercase"
                  />
                </div>
                <div>
                  <label className="block text-[9px] font-black text-slate-400 uppercase tracking-widest mb-1.5 ml-1">
                    Senha
                  </label>
                  <input
                    type="password"
                    required
                    placeholder="MÍNIMO 6 CARACTERES"
                    value={formData.password}
                    onChange={(e) =>
                      setFormData((prev) => ({
                        ...prev,
                        password: e.target.value,
                      }))
                    }
                    className="w-full px-4 py-3 bg-slate-50 border border-slate-200 rounded focus:border-[var(--color-brand-dark)] focus:ring-0 transition-all font-mono text-xs text-slate-700 placeholder:text-slate-300 uppercase"
                  />
                </div>
              </div>

              <div className="flex justify-end">
                <button
                  type="button"
                  onClick={() => {
                    setIsRecovering(true);
                    setError(null);
                  }}
                  className="text-[10px] font-bold text-indigo-500 uppercase tracking-widest hover:text-indigo-700"
                >
                  Esqueci minha senha
                </button>
              </div>

              <button
                type="submit"
                disabled={loading}
                className="w-full flex items-center justify-center gap-4 bg-[var(--color-brand-dark)] text-white py-4 rounded font-black shadow-lg hover:shadow-xl hover:bg-black transition-all group disabled:opacity-50 uppercase text-xs tracking-widest"
              >
                <LogIn className="w-4 h-4" />
                {loading ? "AUTENTICANDO..." : "Acessar Painel"}
              </button>

              <div className="mt-8 pt-8 border-t border-slate-100 flex flex-col items-center gap-2">
                <span className="text-[9px] font-black text-slate-300 uppercase tracking-widest leading-none">
                  Status do Sistema
                </span>
                <span className="text-[9px] font-mono text-emerald-500 flex items-center gap-1.5 uppercase font-bold">
                  <span className="w-1.5 h-1.5 bg-emerald-500 rounded-full animate-pulse" />
                  Banco de Dados Interno (Ativo)
                </span>
              </div>
            </form>
          )}
        </div>
      </motion.div>
    </div>
  );
}
